data:
  raw_data_path: data/raw_data/new_raw_data_polygon.csv
preprocessing:
  log_transformation:
    enabled: true
    exclude_no_columns: true
    method: log1p
  scaling:
    enabled: true
    exclude_no_columns: true
    method: standard
umap:
  enabled: true
  include_all_columns: true
  n_neighbors: 15
  n_components: 2
  metric: cosine
  min_dist: 0.05
  random_state: 42
hdbscan:
  min_cluster_size: 50
  min_samples: 15
  metric: euclidean
