#Configurations for relative clustering algortithms 

data:
  raw_data_path: "data/raw_data/new_raw_data_polygon.csv"


preprocessing:
  log_transformation:
    enabled: true
    exclude_columns:
      - "TX_PER_MONTH"
      - "ACTIVE_DURATION_DAYS"
    method: "log1p"  # Use log1p for handling zero/negative values
  
  scaling:
    enabled: true
    method: "standard"  # StandardScaler
    exclude_columns: []  # Add any columns to exclude from scaling
    # Example: exclude_columns: ["WALLET", "CATEGORY_ID"]


# UMAP Dimensionality Reduction Configuration
umap:
  # Core UMAP parameters
  n_neighbors: 20          # Number of neighbors to consider for manifold approximation (2-100)
  n_components: 10           # Number of dimensions to reduce to
  metric: "cosine"      # Distance metric ("euclidean", "manhattan", "cosine", "correlation", etc.)
  
  # Advanced UMAP parameters
  min_dist: 0.0          # Minimum distance between points in low-dimensional space (0.0-1.0)
  spread: 1.0             # How spread out the embedded points should be (>0.0)
  
  # Learning parameters
  learning_rate: 1.0      # Learning rate for optimization (>0.0)
  n_epochs: null          # Number of training epochs (null for auto)
  init: "spectral"        # Initialization method ("spectral", "random", "pca")
  
  # Reproducibility
  random_state: 42        # Random seed for reproducibility
  
  # Performance parameters
  verbose: true           # Whether to print progress information
  low_memory: false       # Use low memory mode (slower but uses less RAM)
  
  # Advanced metric parameters (for specific metrics)
  metric_kwds: null       # Additional keyword arguments for the metric
  
  # Embedding parameters
  output_metric: "euclidean"     # Metric for the output space
  output_metric_kwds: null       # Additional arguments for output metric
  
  # Negative sampling parameters
  negative_sample_rate: 5        # Number of negative samples per positive sample
  
  # Transform parameters (for new data)
  transform_queue_size: 4.0      # Queue size for approximate nearest neighbor search

  #specialized parameters
  angular_rp_forest: false

  # features to be included in UMAP
  include_columns:
    - "TX_PER_MONTH"
    - "TOKEN_DIVERSITY"
    - "PROTOCOL_DIVERSITY"
    - "INTERACTION_DIVERSITY"
    - "ACTIVE_DURATION_DAYS"
    - "AVG_TRANSFER_USD"
    - "USD_TRANSFER_STDDEV"
    - "DEX_EVENTS"
    - "GAMES_EVENTS"
    - "CEX_EVENTS"
    - "DAPP_EVENTS"
    - "DEFI_EVENTS"
    - "BRIDGE_EVENTS"
    - "NFT_EVENTS"
    - "TOKEN_EVENTS"
    - "BRIDGE_TOTAL_VOLUME_USD"
    # NOTE: Updated UMAP code to include these columns and maintain consistency with preprocessing

# Output Configuration
output:
  save_umap_results: true
  umap_output_path: "data/processed_data/umap_reduced_data.csv"
  save_preprocessing_info: true
  preprocessing_info_path: "data/processed_data/preprocessing_info.yaml"
  # This output configuration is compatible with HDBSCAN clustering plans

# Note: Configuration validity has been validated through the updated UMAP functionality

